### ISSUE TITLE
Example of google-credential.json

### ISSUE THREAD

**Issue by malinkinsa** [omise/graylog-plugin-google-cloud-pubsub#1]
Hello, 
Can you provide an example of google-credential.json? Or we can use downloaded from google account page?

**Comment by KongZ** [comment]
You can create and download from IAM service account page
https://console.cloud.google.com/iam-admin/serviceaccounts

It is a JSON file like this
```
{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": ""
}
```

If you are not sure how to do, follow the Google Cloud document
https://cloud.google.com/iam/docs/service-accounts
